application: acsyshealthguide
version: 2
runtime: python
api_version: 1
builtins:
- datastore_admin: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /static
  static_dir: static 
- url: .*
  script: main.py
- url: /api/healthsdataset/query/(.*)/zip/(.*)/lan/(en|es)/type/(keyword|icd9)/format/(json|xml)
  script: main.py
- url: /api/clinicaltrials/keyword/(.*)/state/(.*)/format/(json|xml)
  script: main.py
- url: /api/healthdata/code/(.*)/lan/(en|es)/format/(json|xml)
  script: main.py
- url: /api/healthdata/code/(.*)
  script: main.py
- url: /api/healthdata/keyword/(.*)/format/(json|xml)
  script: main.py
- url: /api/healthdata/keyword/(.*)
  script: main.py
- url: /api/healthnews
  script: main.py
- url: /api/healthnews/lan/(en|es)/format/(json|xml)
  script: main.py
- url: /api/translate
  script: main.py
- url: /api/healthupdates
  script: main.py
- url: /api/healthupdates/format/(json|xml)
  script: main.py
- url: /api/dialysis-center-search/zip/(.*)/format/(json|xml)
  script: main.py
- url: /api/dialysis-center-search/citystate/(.*)/format/(json|xml)
  script: main.py
- url: /api/dialysis-center-search/geopt/(.*)/format/(json|xml)
  script: main.py
- url: /api/dialysis-center-info/id/(.*)/format/(json|xml)
  script: main.py
- url: /api/hospital-search/condition/(.*)/format/(json|xml)
  script: main.py
- url: /api/hospital-search/zip/(.*)/format/(json|xml)
  script: main.py
- url: /api/hospital-search/citystate/(.*)/format/(json|xml)
  script: main.py
- url: /api/hospital-search/geopt/(.*)/format/(json|xml)
  script: main.py
- url: /api/hospital-info/id/(.*)/format/(json|xml)
  script: main.py